export const FETCH_STATS = 'FETCH_STATS';
export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS';
export const FETCH_STATS_FAILURE = 'FETCH_STATS_FAILURE';
export const SELECT_STATS_PERIOD = 'SELECT_STATS_PERIOD';
